# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: v2tic application

on:
  pull_request:
    branches: [ "talnaser-v2tic" ]
  push:
    branches: [ "talnaser-v2tic" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test regression suite with pytest framework
      working-directory: .
      run: |
        echo "127.0.0.1 https-server.v2tic.com smtp-server.v2tic.com https-listener.v2tic.com smtp-listener.v2tic.com" | sudo tee -a /etc/hosts
        pytest ./tests/api_tests -k regression --capture=tee-sys
        pytest ./tests/unit_tests